### PR TITLE
fix aws full test profiles

### PR DESCRIPTION
**Pull request by ggabernet**
# nf-core/eager pull request
Fixes the AWS full tests profile import in `nextflow.config`.

## PR checklist

- [x] This comment contains a description of changes (with reason)
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If necessary, also make a PR on the [nf-core/eager branch on the nf-core/test-datasets repo](https://github.com/nf-core/test-datasets/pull/new/nf-core/eager)
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --paired_end`).
- [ ] Make sure your code lints ([`nf-core lint .`](https://nf-co.re/tools)).
- [ ] Documentation in `docs` is updated
- [x] `CHANGELOG.md` is updated
- [ ] `README.md` is updated

**Learn more about contributing:** [CONTRIBUTING.md](https://github.com/nf-core/eager/tree/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by ggabernet** [comment]
Is there a reason why you use the `awsfulltest` config instead of the `test_full` config for the AWS full size test workflow? 

It is quite standardized that the rest of the pipelines just use the `test_full` profile for the AWS full tests, so it would be neat to keep it like this in all pipelines, unless there is a specific reason for it, of course 😄

**Comment by jfy133** [comment]
Mmm I don't think there is a particular reason. It is probably a legacy thing from very early on when aws testing was being set up and not yet standardised, right @apeltzer ? (#hipsters). Probably fine to follow the mainstream now.

**Comment by apeltzer** [comment]
Yes I think that's the reason 🙈

**Comment by ggabernet** [comment]
right, you were pioneers with the full dataset testing in AWS!  I've removed it then in exchange for the `test_full` profile. This should hopefully fix the AWS full tests, and with the new workflow dispatch option, they can be triggered manually under the GitHub Actions tab (select the AWS full test workflow) to test if they pass in the dev branch. Once you trigger them, the tests can be followed with Tower and the `nf-core-awstests@mailinator.com` email address to actually know if the pipeline runs through 🤞

**Review by apeltzer — APPROVED** [review]

**Pull request merged**
