### PR TITLE
Docs and tutorials updates

### PR DESCRIPTION
**Pull request by jfy133**
# nf-core/eager pull request

Many thanks for contributing to nf-core/eager!

Please fill in the appropriate checklist below (delete whatever is not relevant).
These are the most common things requested on pull requests (PRs).

## PR checklist

- [ ] This comment contains a description of changes (with reason)
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If necessary, also make a PR on the [nf-core/eager branch on the nf-core/test-datasets repo](https://github.com/nf-core/test-datasets/pull/new/nf-core/eager)
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --paired_end`).
- [ ] Make sure your code lints ([`nf-core lint .`](https://nf-co.re/tools)).
- [ ] Documentation in `docs` is updated
- [ ] `CHANGELOG.md` is updated
- [ ] `README.md` is updated

**Learn more about contributing:** [CONTRIBUTING.md](https://github.com/nf-core/eager/tree/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by ewels** [comment]
@jfy133 - the tutorial about config profiles is great! But it's not specific to the eager pipeline really. What do you think above moving it to the website, maybe at https://nf-co.re/usage/configuration ? Would be great to have it available for the whole @nf-core community!

**Comment by jfy133** [comment]
Thanks @ewels - I was actually trying to put it quietly on EAGER and get some feedback from the aDNA field first. However of course you're right. 

That said I actually just took a stab at combining the two but I'm not finding what I've already written really meshes well with the configuration page, which is already very well written but is sort of talking about a different thing. The way I've written the tutorial is very much like an actual tutorial, and also focuses on the whole institutioanl profile thing rather than profiles for pipeline-specific parameters. I almost feel it would make more sense to have a 'tutorials' section on a webpage, becuse at least what i've written is _trying_ to aim more towards every-day users of the pipeline rather than bioinformaticians with knowledge how clusters/schedulers etc works.

I will keep what I've written already in eager first, but then open an issue and we can discuss it.

**Comment by ewels** [comment]
Ah sorry, you can blame @apeltzer for letting the cat out of the bag 😅 

More and smaller / more specific tutorials for the website would be great 👍 Same logic applies as docs though I think, would be good to keep the more general stuff in a central location rather than tied to pipelines (when you're ready of course!).

The fact that the config page is talking about a different thing is kind of why I thought this would be a good addition. I'm not sure that we really describe profiles as well as this anywhere..

**Comment by apeltzer** [comment]
Sorry, probably was too excited already 😅

**Pull request merged**
