### PR TITLE
Add bam filtering on fragment length script

### PR DESCRIPTION
**Pull request by maxibor**
Add bam filtering on fragment length script

## PR checklist

- [X] This comment contains a description of changes (with reason)
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If necessary, also make a PR on the [nf-core/eager branch on the nf-core/test-datasets repo](https://github.com/nf-core/test-datasets/pull/new/nf-core/eager)
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --paired_end`).
- [ ] Make sure your code lints ([`nf-core lint .`](https://nf-co.re/tools)).
- [ ] Documentation in `docs` is updated
- [ ] `CHANGELOG.md` is updated
- [ ] `README.md` is updated

**Learn more about contributing:** [CONTRIBUTING.md](https://github.com/nf-core/eager/tree/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by jfy133** [comment]
Thanks @maxibor ! @apeltzer this is hopefully to replace the shaky `awk` hack I have... will look next week.

**Comment by drpatelh** [comment]
Nice 👍

**Comment by apeltzer** [comment]
Doesn't add the script to the nextflow code no? We need to test this ;-)

**Comment by jfy133** [comment]
> Doesn't add the script to the nextflow code no? We need to test this ;-) 

That's the plan, don't worry!

**Review by jfy133 — CHANGES_REQUESTED** [review]
Only issue I can see is that: during testing, `-a` seems to do nothing.

```
(samtools) sos@dat4903339:10:28:bwa:(dev)$ samtools stats filtered_py_ohneA.filtered.bam | grep ^FRL | cut -f 2- | head
31	2
32	2
33	2
34	4
35	1
36	4
37	4
38	5
39	4
40	8
(samtools) sos@dat4903339:10:28:bwa:(dev)$ samtools stats filtered_py_withA.filtered.bam | grep ^FRL | cut -f 2- | head
31	2
32	2
33	2
34	4
35	1
36	4
37	4
38	5
39	4
40	8
```

**Comment by maxibor** [comment]
This should now include unmapped reads https://pysam.readthedocs.io/en/latest/api.html#pysam.AlignmentFile.fetch

**Review by jfy133 — APPROVED** [review]
Works for me. Will merge and make a new PR to replace the awk, and hopefully this makes CI more stable :muscle:

**Pull request merged**
