### PR TITLE
Multiqc updates

### PR DESCRIPTION
**Pull request by jfy133**
# nf-core/eager pull request

This includes improvements for the latest MultiQC release, primarily adding new tools (MALT, Kraken, MultiVCFAnalyzer) and better read name cleaning. 

## PR checklist

- [x] This comment contains a description of changes (with reason)
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If necessary, also make a PR on the [nf-core/eager branch on the nf-core/test-datasets repo](https://github.com/nf-core/test-datasets/pull/new/nf-core/eager)
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --paired_end`).
- [x] Make sure your code lints ([`nf-core lint .`](https://nf-co.re/tools)).
- [ ] Documentation in `docs` is updated
- [x] `CHANGELOG.md` is updated
- [x] `README.md` is updated

**Learn more about contributing:** [CONTRIBUTING.md](https://github.com/nf-core/eager/tree/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by jfy133** [comment]
@apeltzer Maybe we can work together on this one here, if there are more improvement sbased on your/Phil's RNAseq stuff

**Comment by jfy133** [comment]
@maxibor Could you tweak the config to include the latest Kraken stuff as well? You probably know best which columns are useful for aDNA

**Comment by maxibor** [comment]
You got it  with 11d713f @jfy133

**Comment by apeltzer** [comment]
Anything missing so far in the report now?

**Comment by jfy133** [comment]
Want to test it a bit and see if I can push Alex H. For the MVA release, but almost there

**Comment by jfy133** [comment]
MultiVCFAnalyzer is now out so I just need to bump the docker

**Pull request merged**
