### PR TITLE
Sex Determintion with error bars

### PR DESCRIPTION
**Pull request by TCLamnidis**
## PR checklist
 - [x] This comment contains a description of changes (with reason)
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [x] If necessary, also make a PR on the [nf-core/eager branch on the nf-core/test-datasets repo]( https://github.com/nf-core/test-datasets/pull/new/nf-core/eager)
 - [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
 - [x] Make sure your code lints (`nf-core lint .`).
 - [x] Documentation in `docs` is updated
 - [x] `CHANGELOG.md` is updated
 - [x] `README.md` is updated

**Learn more about contributing:** https://github.com/nf-core/eager/tree/master/.github/CONTRIBUTING.md

Added Sex determination module, and fixed a minor bug in the which statement of the bwa module.

### CODE REVIEW

**Comment by TCLamnidis** [comment]
Test data should fail, since the mtDNA reference won't have an X/Y chromosome. I have tested this on bams from 1240k capture, using a bedfile, and it worked fine. 
The process can run without a bedfile but it takes considerably longer, and error bars are not informative.

**Comment by TCLamnidis** [comment]
Should a bedfile be packaged with eager?

**Comment by apeltzer** [comment]
> Test data should fail, since the mtDNA reference won't have an X/Y chromosome. I have tested this on bams from 1240k capture, using a bedfile, and it worked fine.

Hm, then we might have to add a separate mini BAM file or similar to test whether this works... e.g some reads extracted from X/Y chromosomes and map them against only X/Y in a separate tests to test this also automatically 👍 You could also add such a BED file for testing purposes and run once with and once without the BED if you want to. 

> The process can run without a bedfile but it takes considerably longer, and error bars are not informative.

This info should be present in the `output.md` description so that users know how to interprete these or know that these are not informative when not using a BED file.

**Comment by jfy133** [comment]
> Hm, then we might have to add a separate mini BAM file or similar to test whether this works... e.g some reads extracted from X/Y chromosomes and map them against only X/Y in a separate tests to test this also automatically +1 You could also add such a BED file for testing purposes and run once with and once without the BED if you want to.

Wouldn't even X/Y chromosomes only be too big a reference for the test datasets?

**Comment by apeltzer** [comment]
> Wouldn't even X/Y chromosomes only be too big a reference for the test datasets?

If we can keep it in the limits - ok, otherwise we might have no separate test for this for non " real testing datasets"... 

(We're working on making full size tests possible in the near future, but stay tuned for updates for a while :-))

**Pull request merged**
