### PR TITLE
Add explanation of sticked on revision

### PR DESCRIPTION
**Pull request by jfy133**
To help with: https://github.com/nf-core/eager/issues/385

## PR checklist

- [x] Documentation in `docs` is updated

### CODE REVIEW

**Comment by jfy133** [comment]
> Could be good to have that in the template in nf-core/tools as well, or in the website directly

Where do you think it would be good to have? I didn't put it on nf-core/tools because it's a nextflow specific behaviour, and I couldn't find a good place to place it on the website (unless maybe troubleshooting?). I put it here specifically because I know that many users of eager will be scared off by the nextflow website ;)

**Comment by MaxUlysse** [comment]
Troubleshooting sounds like a good idea.
And if its really a recurring error for house EAGER, I do understand the need to have it here, but I do think that this kind of general issues would be better in the nf-core website

**Comment by apeltzer** [comment]
I think `Troubleshooting` section on nf-core website sounds like a good idea - can keep it here too if it helps James.

**Comment by jfy133** [comment]
Done! @MaxUlysse @apeltzer Now in nf-core website, but would also like it to be here too.

**Pull request merged**
