### PR TITLE
New logo for darkmode support

### PR DESCRIPTION
**Pull request by jfy133**
This adds a new logo discussed on #graphics to try out improved dark mode compatibility.

If this style is adopted across other pipelines then I will rename everything back down to the template-like file names.

image
image
image

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
  - [ ] If you've added a new tool - add to the software_versions process and a regex to `scrape_software_versions.py`
  - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/eager/tree/master/.github/CONTRIBUTING.md)
  - [ ] If necessary, also make a PR on the nf-core/eager _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint .`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [x] Usage Documentation in `docs/usage.md` is updated.
- [x] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [x] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by jfy133** [comment]
Only thoughts from me:

1) I don't particularly like the logo right-justified  in the README
2) The logo looks  a bit 'cut off' on the MultiQC report (as in the banner goes into nothing)

**Comment by ewels** [comment]
I think that it's especially illegible when small on the MultiQC report.. 😕

I know it was kind of the whole point, but what about just staying simple and using a white outline around text without the green background stripe? Maybe with bonus shadow if you want..

**Comment by jfy133** [comment]
New version

image
image
image


Looks better now, but the outline might be too thick? Thoughts @ewels ?

**Comment by maxulysse** [comment]
I don't think the MultiQC report needs a DarkMode

**Comment by jfy133** [comment]
Agreed but I only want to deal with a single logo file where possible. So this is the original logo but just with the outline (for both readme and MultiQC report)

**Comment by maxulysse** [comment]
I see.
But as we already have a logo for multiQC in assets, it could be done to use 2 different logos depending of the needs.

But I agree, it's not really helping out

**Comment by jfy133** [comment]
I think I'm using the same for both 🤔.

Either way I think this version at least it's overall more portable (even
if a bit boring)

---

**Comment by ewels** [comment]
Looks good!

Another totally different idea - can we find a grey that works for both backgrounds instead of using black text?

**Comment by jfy133** [comment]
To use the colour scheme from the Github website (for semi-consistency), almost a 'silver' grey 

image

And then locking the two github background colours na dcycling through https://coolors.co/

Blue grey

image

Slightly red grey

image

Or bluey again

image


Honestly I think I prefer the black one...

**Comment by jfy133** [comment]
unless you have another idea for a grey @ewels (e.g. if you were thinking darker)

**Comment by TCLamnidis** [comment]
I think Phil's idea was to use a gray that will work on both themes WITHOUT the white border, rather than what you have made here. 

For my two cents, from the grays, blue/blueish greys look nicer than silver grey/redish grey. Though I too prefer the black one overall.
I think that the dark-mode logo with black letters would actually look nicer with a thinner white border than the one you have here. enough to separate it from the background but not enough that it becomes a "noticable" to the point the logo feels like a different thing between light and dark mode.

**Comment by jfy133** [comment]
Ah fair point. Even so finding a nicer grey was quite hard...

But yes can make the outline thinner. Seemed a bit too fat for me too.

**Review by ZandraFagernas — APPROVED** [review]

**Review by TCLamnidis — APPROVED** [review]
LGTM

**Pull request merged**
