### PR TITLE
Help message cleanup and BWA ALN mapping hotfix

### PR DESCRIPTION
**Pull request by jfy133**
This includes:

1. Help mesage formatting
2. Set BWA mem output file prefix  with `.baseName` operator
3. Hotfix for a incorrect bwa aln mapping conditional logic (was missing a negation for the `params.bwamem`)
4. Made FASTQC publishDir directories more logical (one directory for each stage)

## PR checklist
 - [x] This comment contains a description of changes (with reason)
 - [x] If you've fixed a bug or added code that should be tested, add tests!
 - [x] If necessary, also make a PR on the [nf-core/eager branch on the nf-core/test-datasets repo]( https://github.com/nf-core/test-datasets/pull/new/nf-core/eager)
 - [x] Ensure the test suite passes (`nextflow run . -profile test,docker`).
 - [x] Make sure your code lints (`nf-core lint .`).
 - [x] Documentation in `docs` is updated
 - [ ] `CHANGELOG.md` is updated
 - [x] `README.md` is updated

**Learn more about contributing:** https://github.com/nf-core/eager/tree/master/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by jfy133** [comment]
@apeltzer the nf-core linting error looks wierd

```
INFO: ===========
 LINTING RESULTS
=================
  51 tests passed   0 tests had warnings   1 tests failed

ERROR: Test Failures:
  http://nf-co.re/errors#5: Continuous integration must check for master/patch branch PRs: '/home/runner/work/eager/eager/.travis.yml'

ERROR: Sorry, some tests failed - exiting with a non-zero error code...


##[error]Process completed with exit code 1.
```

The yaml is definitely in the repo, but why does the path have eager twice? Is that expected?

**Comment by ewels** [comment]
The path is just the local path to the pipeline code. Is there two directories called eager on your machine?

**Comment by jfy133** [comment]
> The path is just the local path to the pipeline code. Is there two directories called eager on your machine?

@apeltzer ?

**Comment by jfy133** [comment]
> The path is just the local path to the pipeline code. Is there two directories called eager on your machine?

Sorry, it was an issue with the travis file, Alex forgot to update the EAGER YAML after him making the linttng changes. My bad.

**Pull request merged**
