### PR TITLE
Fastq from unmapped reads

### PR DESCRIPTION
**Pull request by maxibor**
To answer #187 
Comes with a python script (using [pysam](https://pysam.readthedocs.io/en/latest/)) to recreate fastq files from the unmapped reads.

**However** this is using Python3 and the Python in the conda env is currently 2.7 :(

### CODE REVIEW

**Comment by jfy133** [comment]
@maxibor are these fastq reads pre Trimming and merging, but without human reads?

**Comment by maxibor** [comment]
Yes

**Comment by maxibor** [comment]
> It even extracts the unmapped data to either BAM, FastQ depending on the users choice. I think we need something else :-(

But this step works on post AR fastq files

**Comment by jfy133** [comment]
Sorry - that close was courtesy of Maia

**Comment by maxibor** [comment]
Updated Conda env so Pysam should work

**Comment by jfy133** [comment]
Looking more in depth (please correct me if I misunderstand anything).

**Major**

I can't comment on the python section. However,

1. The BAM file as input into this tool should be immediately after BWA  (`sorted.bam`) as it should include all possible mapped reads, not just ones that mapped exactly. i.e. if you use the reads post-`samtools filter -q 37`, the discarded _mapped_ reads would not be filtered by the new module, because they are removed from the mapped BAM file after the `samtools filter`.  

2. Is L921 flipped? Shouldn't it be `if (params.singleEnd) {` - as you only indicate a single output file in that conditional block?

**Minor**

For the process name (L906), flag itself  (L363, L218) and help message (L108), I suggest the following extra precision instead of `-unmap`:

```
--strip_input_fastq                       Create pre-Adapter Removal FASTQ files without reads that mapped to reference (e.g. for public upload of privacy sensitive non-host data)
```

publishDir should renamed to something like `/samtools/stripped_fastq` rather than `unmapped_fastq`, as the latter _file_ already exists with the `--extract_unmapped` functionality.

Equally, the output FASTQ names should be e.g. `stripped.fwd.fq.gz` and `stripped.rev.fq.gz` or something. I think `R1`/`R2` would be dangerous for novices re-analyzing the data with the same pipeline, if they forget to add underscores (i.e. there are two `R1`/`R2`s in the name). This may then lead to funky input regex for a EAGER2 re-run and subsequent errors.

**Comment by maxibor** [comment]
Followed the suggestions of @jfy133 
Also user can now choose the strip mode: Either stripping completely the mapped reads (`--strip_mode strip`) or just replace the sequence of the mapped reads by N (`--strip_mode replace`)

**Comment by jfy133** [comment]
@ivelsko owes you a beer ;)

**Comment by maxibor** [comment]
@apeltzer Can you have a look and merge if ok ?
The tests are working with the updated docker image using the new conda env. Travis should be fixed after the docker image is rebuilt.

**Comment by apeltzer** [comment]
Just failing because of missing `python3.6` and `pysam` - merging to get the `dev` image updated 👍

**Pull request merged**
