### PR TITLE
Fix for post-dup steps

### PR DESCRIPTION
**Pull request by apeltzer**
Many thanks to contributing to nf-core/eager!

Please fill in the appropriate checklist below (delete whatever is not relevant). These are the most common things requested on pull requests (PRs).

## PR checklist
 - [x] This comment contains a description of changes (with reason)
 - [x] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] If necessary, also make a PR on the [nf-core/eager branch on the nf-core/test-datasets repo]( https://github.com/nf-core/test-datasets/pull/new/nf-core/eager)
 - [x] Ensure the test suite passes (`nextflow run . -profile test,docker`).
 - [x] Make sure your code lints (`nf-core lint .`).
 - [ ] Documentation in `docs` is updated
 - [x] `CHANGELOG.md` is updated
 - [ ] `README.md` is updated

**Learn more about contributing:** https://github.com/nf-core/eager/tree/master/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by jfy133** [comment]
Testing now!

**Comment by jfy133** [comment]
Almost there  I think:

```
Feb-25 20:45:00.068 [Actor Thread 46] ERROR nextflow.processor.TaskProcessor - Error executing process > 'multiqc'

Caused by:
  Process `multiqc` input file name collision -- There are multiple input files for each of the following file names: software_versions/software_versions_mqc.yaml, damageprofiler/dmgprof.json


Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
Feb-25 20:45:00.072 [Actor Thread 46] DEBUG nextflow.Session - Session aborted -- Cause: Process `multiqc` input file name collision -- There are multiple input files for each of the following file names: softwa
re_versions/software_versions_mqc.yaml, damageprofiler/dmgprof.json

```

**Comment by apeltzer** [comment]
@jfy133 this should be fine now for review - @hesterjvs, this should resolve your remaining issue 👍

**Comment by jfy133** [comment]
See it's closed - but works like a charm on my dataset. Great speedy work @apeltzer, thanks !

**Comment by apeltzer** [comment]
Yeah tested it with some more data and figured this works pretty fine now :-)

**Pull request merged**
