### PR TITLE
Output interpretation Documentation

### PR DESCRIPTION
**Pull request by jfy133**
Many thanks to contributing to nf-core/eager!

Please fill in the appropriate checklist below (delete whatever is not relevant). These are the most common things requested on pull requests (PRs).

## PR checklist
 - [x] This comment contains a description of changes (with reason)

**Learn more about contributing:** https://github.com/nf-core/eager/tree/master/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by jfy133** [comment]
@apeltzer can you look at the damageprofiler text and see if this looks OK?

**Comment by apeltzer** [comment]
Will do :)

**Comment by jfy133** [comment]
Added AdapterRemoval section. Although note I still really don't understand neither the output described in the `.settings`, file, nor the MultiQC plots.

For the latter I'm pretty sure someone made a mistake in including the 'final output reads' as a section of the stacked bar, alongside each category that goes into that  - but it is really confusing.

On the otherhand, maybe _it is_ correct, but I cannot for the life of me make all the numbers in the `.settings` file add up. So my descriptions are purely based on what I understand and are maybe wrong.

@apeltzer do you have any more knowledge on how to make the stats add up properly? We might have discussed this at some point in the context of EAGER1 but lost my notes

**Comment by apeltzer** [comment]
Will have a look soonish :-)

**Comment by jfy133** [comment]
@apeltzer 
@maxibor 
@TCLamnidis 

this could now be in principle included for the next release. This will be improved later with example schematic plots etc., however this draft is now in a usable state.

Could you all go through it and fix any mistakes or misunderstandings on my half? If there is anything unclear let me know and I'll try and rephrase.

**Comment by apeltzer** [comment]
Amazin job :-)

**Pull request merged**
