### PR TITLE
Enable gzipped FastA input as reference genome

### PR DESCRIPTION
**Pull request by apeltzer**
Adds support for gzipped FastA reference genome input.

## PR checklist
 - [x] This comment contains a description of changes (with reason)
 - [x] If you've fixed a bug or added code that should be tested, add tests!
 - [x] Ensure the test suite passes (`nextflow run . -profile test,docker`).
 - [x] Make sure your code lints (`nf-core lint .`).
 - [x] Documentation in `docs` is updated
 - [x] `CHANGELOG.md` is updated

### CODE REVIEW

**Comment by apeltzer** [comment]
Should add support following on https://github.com/nf-core/eager/issues/91

**Comment by apeltzer** [comment]
@jfy133 please review this, then you may request changes and/or merge it :-)

**Comment by apeltzer** [comment]
Would like to stick to review / merge pattern from now on to keep things protected here :-)

**Comment by apeltzer** [comment]
Hm, I don#t get what you mean with this:

- Input FastA.gz (solved by this already)
- Index creation 
- Usage in the pipeline
- ... ? 

Zipping the index doesn't make that much sense, as we'd have to uncompress everytime we use the index again before running something in a pipeline (which is too much overhead ...) .

Or do you mean we should save the indexed reference genome as compressed zip archive as well?

**Comment by jfy133** [comment]
> Hm, I don#t get what you mean with this:
> 
> * Input FastA.gz (solved by this already)
> * Index creation
> * Usage in the pipeline
> * ... ?
> 
> Zipping the index doesn't make that much sense, as we'd have to uncompress everytime we use the index again before running something in a pipeline (which is too much overhead ...) .
> 
> Or do you mean we should save the indexed reference genome as compressed zip archive as well?

The latter. But this is still a rare case I imagine. 

Just accepting a gzipped reference the first time the reference is used would be a sufficient purpose of this functionality (e.g. genomes downloaded from NCBI are gzipped).

Maybe keep this commit as it is for the moment. If someone else requests a recompressed indexed FASTA we can consider that later.

**Pull request merged**
