### PR TITLE
Release 2.0.7

### PR DESCRIPTION
**Pull request by apeltzer**
This is a maintenance release for a couple of neat fixes in the pipeline  👍 

## PR checklist
 - [x] This comment contains a description of changes (with reason)
 - [x] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] If necessary, also make a PR on the [nf-core/eager branch on the nf-core/test-datasets repo]( https://github.com/nf-core/test-datasets/pull/new/nf-core/eager)
 - [x] Ensure the test suite passes (`nextflow run . -profile test,docker`).
 - [x] Make sure your code lints (`nf-core lint .`).
 - [x] Documentation in `docs` is updated
 - [x] `CHANGELOG.md` is updated
 - [ ] `README.md` is updated

### CODE REVIEW

**Comment by jfy133** [comment]
I'm still having issues with `strip_input_fastq`:

```
Apr-14 20:18:42.093 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'strip_input_fastq (ABM006.A0101_S0_L003_R1_001.fastq.combined.fq.gz.baseName}.sorted)'
 
Caused by: 
  Process `strip_input_fastq (ABM006.A0101_S0_L003_R1_001.fastq.combined.fq.gz.baseName}.sorted)` terminated with an error exit status (1)
 
Command executed:

  samtools index ABM006.A0101_S0_L003_R1_001.fastq.combined.fq.gz.baseName}.sorted.bam
  extract_map_reads.py ABM006.A0101_S0_L003_R1_001.fastq.combined.fq.gz.baseName}.sorted.bam ABM006.A0101_S0_L004_R1_001.fastq.gz -rev ABM006.A0101_S0_L004_R2_001.fastq.gz -m  strip -of ABM006.A0101_S0_L003_R1_001.fastq.combined.fq.gz.baseName}.sorted.stripped.fwd.fq.gz -or ABM006.A0101_S0_L003_R1_001.fastq.combined.fq.gz.baseName}.sorted.stripped.rev.fq.gz -p 8

Command exit status: 
  1

Command output: 
  (empty)

Command error: 
  Traceback (most recent call last):
    File "/projects1/clusterhomes/fellows/.nextflow/assets/nf-core/eager/bin/extract_map_reads.py", line 238, in <module>
      mapped_reads = extract_mapped(BAM, PROC) 
    File "/projects1/clusterhomes/fellows/.nextflow/assets/nf-core/eager/bin/extract_map_reads.py", line 93, in extract_mapped
      p = multiprocessing.Pool(processes)
    File "/opt/conda/envs/nf-core-eager-2.0.7/lib/python3.6/multiprocessing/context.py", line 119, in Pool 
      context=self.get_context())
    File "/opt/conda/envs/nf-core-eager-2.0.7/lib/python3.6/multiprocessing/pool.py", line 157, in __init__
      self._setup_queues() 
    File "/opt/conda/envs/nf-core-eager-2.0.7/lib/python3.6/multiprocessing/pool.py", line 271, in _setup_queues
      self._inqueue = self._ctx.SimpleQueue()
    File "/opt/conda/envs/nf-core-eager-2.0.7/lib/python3.6/multiprocessing/context.py", line 112, in SimpleQueue 
      return SimpleQueue(ctx=self.get_context())
    File "/opt/conda/envs/nf-core-eager-2.0.7/lib/python3.6/multiprocessing/queues.py", line 315, in __init__
      self._rlock = ctx.Lock() 
    File "/opt/conda/envs/nf-core-eager-2.0.7/lib/python3.6/multiprocessing/context.py", line 67, in Lock
      return Lock(ctx=self.get_context())
    File "/opt/conda/envs/nf-core-eager-2.0.7/lib/python3.6/multiprocessing/synchronize.py", line 162, in __init__ 
      SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
    File "/opt/conda/envs/nf-core-eager-2.0.7/lib/python3.6/multiprocessing/synchronize.py", line 59, in __init__
      unlink_now) 
  FileNotFoundError: [Errno 2] No such file or directory

Work dir: 
  /projects1/users/fellows/nextflow/eager2/dev_testing/eager2/01-actual_reference/tannerella_forsythia/ABM006.A0101/work/da/2c06e66b4a46a78c42ffbae8640449
```

@maxibor

**Comment by jfy133** [comment]
One for @apeltzer, DamageProfiler is failing even though there are 4k reads mapping to the genome (more than enough for damage patterns). Correct me if I'm wrong, but it looks like it might be a programming typo? 

I'm now wondering if ignoring DamageProfiler errors is a good idea now. Is it possible to make DamageProfiler to spit out a particular error code if no input reads, and get nextflow to ignore that specific error instead?

```
[82/0be399] NOTE: Missing output file(s) `ABM006.A0101_S0_L002_R1_001.fastq.combined.fq.gz.baseName}.sorted/dmgprof.json` expected by process `damageprofiler (ABM006.A0101_S0_L002_R1_001.fastq.combined.fq.gz.baseName}.sorted)` -- Error is ignored
[1c/a3bc6b] NOTE: Missing output file(s) `ABM006.A0101_S0_L004_R1_001.fastq.combined.fq.gz.baseName}.sorted/dmgprof.json` expected by process `damageprofiler (ABM006.A0101_S0_L004_R1_001.fastq.combined.fq.gz.baseName}.sorted)` -- Error is ignored
[7f/2d5492] NOTE: Missing output file(s) `ABM006.A0101_S0_L001_R1_001.fastq.combined.fq.gz.baseName}.sorted/dmgprof.json` expected by process `damageprofiler (ABM006.A0101_S0_L001_R1_001.fastq.combined.fq.gz.baseName}.sorted)` -- Error is ignored
[a1/e49820] NOTE: Missing output file(s) `ABM006.A0101_S0_L003_R1_001.fastq.combined.fq.gz.baseName}.sorted/dmgprof.json` expected by process `damageprofiler (ABM006.A0101_S0_L003_R1_001.fastq.combined.fq.gz.baseName}.sorted)` -- Error is ignored

```

**Comment by jfy133** [comment]
For a similar issue to the DamageProfiler possible typo, when supplying my own `bwa` and `samtools faidx` indices, I hit a similar issue (by the looks of things).

This is the command:

```
nextflow run nf-core/eager \
-profile shh \
--reads '/projects1/users/fellows/nextflow/eager2/dev_testing/data/ABM006.A0101/*_R{1,2}*fastq.gz' \
--pairedEnd \
--fasta '/projects1/users/fellows/nextflow/eager2/dev_testing/references/tannerella_forsythia_actual/Tannerella_forsythia_9212.fa' \
--bwa_index '/projects1/users/fellows/nextflow/eager2/dev_testing/references/tannerella_forsythia_actual/' \
--fastq_index '/projects1/users/fellows/nextflow/eager2/dev_testing/references/tannerella_forsythia_actual/Tannerella_forsythia_9212.fa.fai' \
--outdir '/projects1/users/fellows/nextflow/eager2/dev_testing/eager2/01-actual_reference/tannerella_forsythia/ABM006.A0101' \
--name 'eager_nextflow_dev' \
--email fellows@shh.mpg.de \
--min_adap_overlap 1 \
--clip_readlength 30 \
--clip_min_read_quality 20 \
--bwaalnn 0.01 \
--bwalnl 32 \
--bam_discard_unmapped \
--bam_unmapped_type fastq \
--dedupper dedup \
--dedup_all_merged \
-r dev
```

The error:

```
Apr-14 20:36:52.879 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'bwa (ABM006.A0101_S0_L002_R1_001.fastq)'

Caused by:
  Process `bwa (ABM006.A0101_S0_L002_R1_001.fastq)` terminated with an error exit status (1)

Command executed:

  bwa aln -t 8 tannerella_forsythia_actual/ ABM006.A0101_S0_L002_R1_001.fastq.combined.fq.gz -n 0.01 -l 32 -k 2 -f ABM006.A0101_S0_L002_R1_001.fastq.combined.fq.gz.baseName}.sai
  bwa samse -r "@RG\tID:ILLUMINA-ABM006.A0101_S0_L002_R1_001.fastq.combined.fq.gz.baseName}\tSM:ABM006.A0101_S0_L002_R1_001.fastq.combined.fq.gz.baseName}\tPL:illumina" tannerella_forsythia_actual/ ABM006.A0101$
  samtools index "-c" "ABM006.A0101_S0_L002_R1_001.fastq.combined.fq.gz.baseName}".sorted.bam

Command exit status:
  1

Command output:
  (empty)

Command error:
  [bwa_aln] 17bp reads: max_diff = 2
  [bwa_aln] 22bp reads: max_diff = 3
  [bwa_aln] 42bp reads: max_diff = 4
  [bwa_aln] 64bp reads: max_diff = 5
  [bwa_aln] 90bp reads: max_diff = 6
  [bwa_aln] 117bp reads: max_diff = 7
  [bwa_aln] 146bp reads: max_diff = 8
  [bwa_aln] 176bp reads: max_diff = 9
  [bwa_aln] 207bp reads: max_diff = 10
  [bwa_aln] 239bp reads: max_diff = 11
  [bwa_aln] fail to locate the index

Work dir:
  /projects1/users/fellows/nextflow/eager2/dev_testing/eager2/01-actual_reference/tannerella_forsythia/ABM006.A0101/work/41/3090dae10997315679d395cb65db35
```

**Comment by apeltzer** [comment]
We Need automated tests for these

**Comment by apeltzer** [comment]
This is not covered by the tests yet unfortunately

**Comment by jfy133** [comment]
> We Need automated tests for these

Indeed. To try and cover the most ground in as few tests as possible the corresponding cases would be some along the lines of:

1. Mammoth_MT_Krause.fasta (+ no indices)
2. Mammoth_MT_Krause.fasta (+ with bwa indices + samtools indices + picard indices)
3. Mammoth_MT_Krause.fna (+ no indices)
4. Mammoth_MT_Krause.fa (+ with bwa indices + samtools indices + picard indices))

Or more extensively:

**Standard input FASTA suffix**
1. Mammoth_MT_Krause.fasta (+ no indices)
2. Mammoth_MT_Krause.fasta (+ with bwa indices)
3. Mammoth_MT_Krause.fasta (+ with bwa indices + samtools indices)
4. Mammoth_MT_Krause.fasta (+ with bwa indices + samtools indices + picard indices)

**Non-standard input FASTA suffix**
1. Mammoth_MT_Krause.fna (+ no indices)
2. Mammoth_MT_Krause.fna (+ with bwa indices)
3. Mammoth_MT_Krause.fna (+ with bwa indices + samtools indices)
4. Mammoth_MT_Krause.fna (+ with bwa indices + samtools indices + picard indices)

For setting up, this would mostly just require copying the Mammoth_MT_Krause.fasta with new suffixes, and only keeping some with indices, depending how important this is.

**Comment by apeltzer** [comment]
Problematic: I think we need a build matrix for this, the maximum runtime per job is 50mins so we need to test this accordingly

**Comment by apeltzer** [comment]
Ok I added some more automated tests using a different PR, so this should update in a minute and test everything accordingly again 👍 If your problem then persists, we might need to figure out whats going on :-)

**Comment by jfy133** [comment]
I'll test again this evening. Can you ping me when the docker build is completed @apeltzer

**Comment by apeltzer** [comment]
I will close this until we have some final tested version on `dev`. Please test with `dev` after I merge my stuff in today :+1:

**Pull request closed without merging**
