### PR TITLE
Bedtools module for reference feature stats

### PR DESCRIPTION
**Pull request by jfy133**
This adds the ability to get depth (X fold) and breadth coverage (%) for annotations (as described in a GFF/BED file) of the reference genome. This is useful for looking for presence/absence of genes (e.g. virulence factors). 

This can also be used for multi-reference (aka 'competitive mapping'), if a multi-fasta of multiple-genomes is used as a reference, and a corresponding bed file is created.

## PR checklist
 - [x] This comment contains a description of changes (with reason)
 - [x] If you've fixed a bug or added code that should be tested, add tests!
 - [x] If necessary, also make a PR on the [nf-core/eager branch on the nf-core/test-datasets repo]( https://github.com/nf-core/test-datasets/pull/new/nf-core/eager)
 - [x] Ensure the test suite passes (`nextflow run . -profile test,docker`).
 - [x] Make sure your code lints (`nf-core lint .`).
 - [x] Documentation in `docs` is updated
 - [x] `CHANGELOG.md` is updated
 - [x] `README.md` is updated

**Learn more about contributing:** https://github.com/nf-core/eager/tree/master/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by jfy133** [comment]
I also added a better job naming system so easier to find on the nf-core tower.nf.

This is: `eager-<branch_name>_<travis_build_ID>-<test_description>`

**Comment by jfy133** [comment]
@apeltzer The tests did actually pass - not sure what the missing CI checks are referring to.

**Comment by apeltzer** [comment]
Ahem. Do we need BEDTools for this? Qualimap can do the same when supplied with an appropriate GTF/BED ?

**Comment by jfy133** [comment]
I didn't know qualimap allowed GFF files, most of the time in the docs it refers to 'GTF' files, which I'm not familiar with.

I'll investigate to see if it's a suitable replacement (with extracting feature coverage data for downstream analysis etc.)

**Comment by jfy133** [comment]
> Ahem. Do we need BEDTools for this? Qualimap can do the same when supplied with an appropriate GTF/BED ?

Just looked - it doesn't do what I want. All reported stats are for features only (also summed across all features, for each feature separately). This works fine for e.g. SNP capture data, but not for bacterial stuff when you want to look at both a) whole genome coverage, and b) feature specific stats.

If you look at the headers of the attached, all stats have `(inside of regions)` in section headers.

[JK2782_TGGCCGATCAACGA_L008_R1_001.fastq.gz.tengrand.fq.combined.fq.mapped_rmdup_stats.zip](https://github.com/nf-core/eager/files/3828940/JK2782_TGGCCGATCAACGA_L008_R1_001.fastq.gz.tengrand.fq.combined.fq.mapped_rmdup_stats.zip)

I would like to proceed with the PR, as this is (mainly) targeted at bacterial functional work.

**Pull request merged**
